### ISSUE TITLE
The website doesn't seem to work

### ISSUE THREAD

**Issue by MgTheProgrammer** [solipsia/RunEveryStreet#3]
The website doesn't load any map to zoom into. choosing to ignore this I've clicked on the button anyway and it got stuck on loading map data.

**Comment by solipsia** [comment]
Thanks for raising this. OpenLayers had removed their legacy API script when they upgraded to a new version. I've fixed it now. Please try again.

**Comment by solipsia** [comment]
@MgTheProgrammer  How did you find this site by the way? Using it for anything interesting?

**Comment by MgTheProgrammer** [comment]
> Thanks for raising this. OpenLayers had removed their legacy API script when they upgraded to a new version. I've fixed it now. Please try again.

Thanks!  It's appreciated that you took the time to fix this issue and doing it so fast. Your website is so cool btw love that I can see the routes being generated.

> @MgTheProgrammer How did you find this site by the way? Using it for anything interesting?

I'm thinking about running or walking every street in my city and inviting the community to join me along the week. I've searched GitHub for CPP solver using data from a map and stumbled upon your repo.
@solipsia
