### ISSUE TITLE
algorithm uses brute force

### ISSUE THREAD

**Issue by michael-ts** [solipsia/RunEveryStreet#4]
I was referred to this page and just assumed it would use the standard polynomial time algorithm available for an undirected route (https://en.wikipedia.org/wiki/Chinese_postman_problem#Undirected_solution_and_T-joins).  After a few hours I came back and was surprised to find it still chugging away with over 1.3 million routes examined.    Any plans to use a faster algorithm that will find the actual best route rather than having to run for a few hours and hope it finds the best solution in that time?

**Comment by solipsia** [comment]
No not really. I created this whole thing over a weekend before a run I was planning on the Sunday and it is more than quick enough to cover any distance I could reasonably run! To be honest I don't understand most of the words in the article you linked. If you want to improve it, feel free to create a fork or a pull request?
